CREATE TABLE MATERIAIS(
  REFERENCIA NUMBER PRIMARY KEY,
  DESIGNACAO VARCHAR2(50),
  CUSTO NUMBER
);

CREATE TABLE OPERACAO(
    ID_OPERACAO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(50)
);

CREATE TABLE CLIENTE(
    NOME VARCHAR2(50),
    NIF NUMBER UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    NUMERO_CARTA NUMBER UNIQUE,
    VALIDADE_CARTA DATE,
    CONTACTO NUMBER,
    ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE VEICULO(
    MATRICULA VARCHAR2(10) PRIMARY KEY,
    MODELO VARCHAR2(10),
    DATA_FABRICO DATE NOT NULL,
    DATA_PRIMEIRA_COMPRA DATE,
    ID_CLIENTE NUMBER
);

CREATE TABLE MARCA(
    NOME_MARCA VARCHAR2(50) UNIQUE,
    ID_MARCA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE MODELO (
    NOME_MODELO VARCHAR2(50),
    ID_MODELO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    QUILOMETROS_MANUTENCAO NUMBER NOT NULL,
    ID_MARCA NUMBER
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_NASCIMENTO DATE NOT NULL,
    NIF NUMBER UNIQUE,
    CONTACTO NUMBER UNIQUE,
    EMAIL VARCHAR2(50) UNIQUE
);


CREATE TABLE INTERVENCAO(
    ID_INTERVENCAO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(50),
    DUACAO_MAXIMA_INTERVENCAO NUMBER(5,3),
    ID_OPERACAO NUMBER,
    CUSTO_TOTAL_INTERVENCAO NUMBER(5,3),
    DATE_INTERVENCAO DATE NOT NULL,
    QUILOMETROS_ACTUAIS NUMBER(5,3) NOT NULL,
    ID_FUNCIONARIO NUMBER,
    MATRICULA VARCHAR2(10)
);


CREATE TABLE MATERIAIS_INTERVENCAO(
    REFERENCIA_MATERIAL NUMBER,
    ID_INTERVENCAO NUMBER
);


ALTER TABLE MATERIAIS_INTERVENCAO ADD CONSTRAINT fk_id_material FOREIGN KEY (REFERENCIA_MATERIAL) REFERENCES MATERIAIS (REFERENCIA);
ALTER TABLE MATERIAIS_INTERVENCAO ADD CONSTRAINT fk_id_intervencao FOREIGN KEY (ID_INTERVENCAO) REFERENCES INTERVENCAO (ID_INTERVENCAO);
ALTER TABLE MATERIAIS_INTERVENCAO ADD CONSTRAINT pk_id_material_id_intervencao PRIMARY KEY (REFERENCIA_MATERIAL, ID_INTERVENCAO);

ALTER TABLE INTERVENCAO ADD CONSTRAINT fk_id_funcionario FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO);
ALTER TABLE INTERVENCAO ADD CONSTRAINT fk_matricula_veiculo FOREIGN KEY (MATRICULA) REFERENCES VEICULO (MATRICULA);
ALTER TABLE INTERVENCAO ADD CONSTRAINT fk_id_operacao FOREIGN KEY (ID_OPERACAO) REFERENCES OPERACAO (ID_OPERACAO);


ALTER TABLE MODELO ADD CONSTRAINT fk_id_marca FOREIGN KEY (ID_MARCA) REFERENCES MARCA (ID_MARCA);

ALTER TABLE VEICULO ADD CONSTRAINT fk_id_cliente FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

